spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:db/changeLog.xml
keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER}
  resource: ${KEYCLOAK_RESOURCE}
  principal-attribute: sub
  credentials:
    secret: ${KEYCLOAK_RESOURCE_PASSWORD}
  bearer-only: true