spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
  datasource:
    adapter: mysql
    encoding: utf-8
    url: ${DB_URL}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:db/changeLog.xml